### PR TITLE
seriously, wow. so many global leaks. such bad, very leak.

### PR DESCRIPTION
**Pull request by deoxxa**

### CODE REVIEW

**Comment by monstrfolk** [comment]
can this get merged please?

**Comment by micahlmartin** [comment]
Merged. I don't maintain this any more so use at your own risk.

**Comment by deoxxa** [comment]
wow, I don't remember this at all. I wonder why I made this PR all that time ago... A mystery!

**Comment by monstrfolk** [comment]
I hope you had good reason for it.

**Pull request merged**
